spring:
  application:
    name: splav
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 600000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080